version : "3.9"
services:

  backend:
    build: .
    ports:
     - "8000:8000"
    container_name: front-gopredict
    volumes:
     - ./saved_models:/app/saved_models
     - ./output:/app/output

  frontend:
    build: ./frontend
    ports:
     - "3000:80"
    container_name: back-gopredict 
    depends_on:
     - backend